Repository workarea-commerce/workarea, pull requests merged in 2019-10, with the labels that each got.

#121 Remove Refund Tests
  core/lib/workarea/configuration.rb
  core/test/models/workarea/payment/credit_card_integration_test.rb
Labels: enhancement

#133 v3.4.17 Patch Release Notes
  docs/source/release-notes.html.md
  docs/source/release-notes/workarea-3-4-17.html.md
Labels: documentation

#125 Update search docs for v3.5
  docs/source/articles/analyze-storefront-search-results.html.md
  docs/source/articles/index-storefront-search-documents.html.md
  docs/source/articles/searching.html.md
  docs/source/articles/storefront-search-features.html.md
Labels: documentation

#136 Fix test failure due to iframe loading
  storefront/test/system/workarea/storefront/release_browsing_system_test.rb
Labels: bug

#128 Pass Options To `Storefront::UserActivityViewModel`
  storefront/app/controllers/workarea/storefront/recent_views_controller.rb
  storefront/app/view_models/workarea/storefront/user_activity_view_model.rb
  storefront/test/integration/workarea/storefront/recent_views_integration_test.rb
  storefront/test/view_models/workarea/storefront/user_activity_view_model_test.rb
Labels: bug

#127 Remove Combined Tax column from Tax Rates index table (#96)
  admin/app/views/workarea/admin/tax_rates/index.html.haml
  admin/test/system/workarea/admin/tax_categories_system_test.rb
Labels: enhancement

#126 Improve order of changesets in Timeline UI (#124)
  admin/app/view_models/workarea/admin/timeline_view_model.rb
  admin/app/views/workarea/admin/timeline/show.html.haml
  admin/config/locales/en.yml
  admin/test/view_models/workarea/admin/timeline_view_model_test.rb
Labels: enhancement

#120 Surface Asset alt text and behavior within Content Blocks (#95)
  admin/app/views/workarea/admin/content_assets/_summary.html.haml
  admin/app/views/workarea/admin/content_assets/index.html.haml
  admin/app/views/workarea/admin/content_blocks/_asset.html.haml
  admin/config/locales/en.yml
  core/config/initializers/14_content_block_types.rb
Labels: enhancement

#115 Spruce up Timeline UI
  admin/app/assets/stylesheets/workarea/admin/components/_activity.scss
  admin/app/assets/stylesheets/workarea/admin/components/_activity_group.scss
  admin/app/assets/stylesheets/workarea/admin/components/_date_marker.scss
  admin/app/views/workarea/admin/activities/show.html.haml
  admin/app/views/workarea/admin/orders/timeline.html.haml
  admin/app/views/workarea/admin/style_guides/components/_activity.html.haml
  admin/app/views/workarea/admin/style_guides/components/_activity_group.html.haml
  admin/app/views/workarea/admin/style_guides/components/_release_changeset.html.haml
  admin/app/views/workarea/admin/timeline/show.html.haml
  admin/app/views/workarea/admin/trash/index.html.haml
  admin/config/locales/en.yml
  admin/test/system/workarea/admin/orders_system_test.rb
Labels: enhancement

#110 Fix Self-Referential Category Rules
  admin/app/controllers/workarea/admin/catalog_categories_controller.rb
  admin/app/views/workarea/admin/product_rules/fields/_category.html.haml
  admin/config/locales/en.yml
  admin/test/integration/workarea/admin/categories_integration_test.rb
Labels: bug

#146 `_id` Suffix Omitted From Customized Fields
  core/app/models/workarea/catalog/customizations.rb
  core/test/models/workarea/catalog/customizations_test.rb
Labels: bug

#113 Fix Product URL In Breadcrumbs
  core/app/models/workarea/navigation/breadcrumbs.rb
  core/test/models/workarea/navigation/breadcrumbs_test.rb
  storefront/app/view_models/workarea/storefront/product_view_model.rb
  storefront/test/helpers/workarea/storefront/navigation_helper_test.rb
  storefront/test/helpers/workarea/storefront/schema_org_helper_test.rb
Labels: bug

#150 Clean up Segments UI Front-End
  admin/app/assets/javascripts/workarea/admin/application.js.erb
  admin/app/assets/javascripts/workarea/admin/modules/active_by_segment_tooltips.js
  admin/app/assets/javascripts/workarea/admin/modules/select2.js
  admin/app/assets/javascripts/workarea/admin/modules/selects.js
  admin/app/assets/javascripts/workarea/admin/modules/toggle.js
  admin/app/assets/javascripts/workarea/admin/modules/toggle_elements.js
  admin/app/views/workarea/admin/content/_form.html.haml
  admin/app/views/workarea/admin/segments/_publish.html.haml
  admin/app/views/workarea/admin/shared/_active_field.html.haml
  admin/config/locales/en.yml
  admin/test/system/workarea/admin/segments_system_test.rb
Labels: enhancement

#160 Improve Mailer Documentation
  docs/source/articles/system-emails.html.md
Labels: documentation
