Repository workarea-commerce/workarea, pull requests merged in 2019-11, with the labels that each got.

#209 Fix Incorrect Test Setup
  core/test/models/workarea/pricing/calculators/tax_calculator_test.rb
Labels: bug

#207 Rename and update doc for testing CC transactions
  docs/data/articles.yml
  docs/source/articles/manually-test-credit-card-transactions.html.md
  docs/source/articles/test-a-credit-card-transaction.html.md
Labels: documentation

#226 Improve table of contents for docs
  docs/source/javascripts/site.js
Labels: documentation

#231 Update v3.5 release notes and upgrade guide
  docs/source/release-notes/workarea-3-5-0.html.md
  docs/source/upgrade-guides/workarea-3-5-0.html.md
Labels: documentation

#237 Improve presentation of code within links
  docs/source/stylesheets/_typography.scss
Labels: documentation

#239 Update Tests Referencing 2020
  storefront/test/integration/workarea/storefront/checkout_side_effects_integration_test.rb
  storefront/test/integration/workarea/storefront/checkouts_integration_test.rb
  storefront/test/integration/workarea/storefront/impersonations_integration_test.rb
  storefront/test/integration/workarea/storefront/order_data_integration_test.rb
  storefront/test/integration/workarea/storefront/place_order_integration_test.rb
  storefront/test/integration/workarea/storefront/placing_order_integration_test.rb
  storefront/test/integration/workarea/storefront/store_credit_integration_test.rb
  storefront/test/integration/workarea/storefront/users/credit_cards_integration_test.rb
  testing/lib/workarea/testing/factories/payment.rb
Labels: enhancement

#243 Import UTF-8 CSVs With BOM Characters
  core/lib/workarea/configuration.rb
  core/test/models/workarea/data_file/csv_test.rb
Labels: bug

#240 Ensure UTF-8 Encoding of Data File Import Samples
  admin/app/controllers/workarea/admin/data_file_imports_controller.rb
  admin/app/views/workarea/admin/data_file_imports/new.html.haml
  admin/test/integration/workarea/admin/data_file_imports_integration_test.rb
  core/app/models/workarea/data_file/operation.rb
Labels: enhancement
