Repository workarea-commerce/workarea, pull requests merged in 2019-09, with the labels that each got.

#81 Display Referrer URL in tooltip on Order Attributes in Admin
  admin/app/assets/javascripts/workarea/admin/application.js.erb
  admin/app/views/workarea/admin/orders/attributes.html.haml
  admin/config/locales/en.yml
  admin/test/system/workarea/admin/orders_system_test.rb
  core/app/assets/javascripts/workarea/core/modules/copy_to_clipboard.js
  core/config/locales/en.yml
Labels: enhancement

#108 Remove /wish_lists entry from Robots.txt
  storefront/app/views/workarea/storefront/pages/robots.text.erb
Labels: enhancement

#107 Remove Schema.org structured data from unspiderable pages
  storefront/app/views/layouts/workarea/storefront/checkout.html.haml
  storefront/app/views/workarea/storefront/cart_items/create.html.haml
  storefront/app/views/workarea/storefront/carts/show.html.haml
  storefront/app/views/workarea/storefront/orders/_summary.html.haml
  storefront/app/views/workarea/storefront/orders/show.html.haml
  storefront/app/views/workarea/storefront/recommendations/show.html.haml
  storefront/app/views/workarea/storefront/searches/show.html.haml
  storefront/app/views/workarea/storefront/users/accounts/edit.html.haml
  storefront/app/views/workarea/storefront/users/accounts/show.html.haml
  storefront/app/views/workarea/storefront/users/addresses/edit.html.haml
  storefront/app/views/workarea/storefront/users/addresses/new.html.haml
  storefront/app/views/workarea/storefront/users/credit_cards/edit.html.haml
  storefront/app/views/workarea/storefront/users/credit_cards/new.html.haml
  storefront/app/views/workarea/storefront/users/orders/index.html.haml
  storefront/app/views/workarea/storefront/users/orders/show.html.haml
  storefront/app/views/workarea/storefront/users/passwords/new.html.haml
Labels: enhancement

#105 refine documentation and docker workflow triggers
  .github/workflows/demo.yml
  .github/workflows/documentation.yml
Labels: enhancement

#89 Add config field to limit total item count for a single cart
  core/app/models/workarea/order.rb
  core/config/initializers/00_configuration.rb
  core/config/locales/en.yml
  core/test/models/workarea/order_test.rb
Labels: enhancement

#70 Replace App Template Command With Install Generator in Upgrade Docs
  docs/source/upgrade-guides/workarea-3-4-0.html.md
Labels: documentation

#123 Fix duplication in README
  README.md
Labels: documentation

#122 Fix information about seeded emails/passwords
  docs/source/articles/seeds.html.md
Labels: documentation

#119 Remove usage of undefined #second method on Array
  .github/actions/build_documentation/documentation/s3.rb
  workarea.gemspec
Labels: bug

#118 Add Inverse Aspect Ratio To Product Image Fields
  core/app/models/workarea/catalog/product_image.rb
  core/test/models/workarea/catalog/product_image_test.rb
Labels: enhancement

#129 Lock Faraday down to 0.15.x
  Gemfile
Labels: bug
